export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_CART = "CHANGE_CART";
export const EDIT_ACTIVE_ATTRIBUTE = "EDIT_ACTIVE_ATTRIBUTE";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const MAIN_OVERLAY = "MAIN_OVERLAY";
